name: PR Auto Comment

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Thank you for your contribution! 🎉

              #### PR Checklist
              - [ ] Tests added/updated
              - [ ] Documentation updated
              - [ ] Changes follow coding standards
              - [ ] Commit messages are clear

              #### Next Steps
              1. We will review your PR soon
              2. Address any requested changes
              3. Once approved, your PR will be merged

              Need help? Check our [Contributing Guide](https://github.com/Mujtabaa07/coffeeShop/blob/main/CONTRIBUTING.md)


              Happy coding! 💻`
            })